language: clojure
lein: lein2
script:
  - lein2 midje
  - lein2 eastwood
branches:
  only:
    - master
    - dev
jdk:
  - oraclejdk7
services:
  - redis
notifications:
  hipchat:
    rooms:
      - ec1ead2b384476ea5bcb232b5bb9b6@Snooty Monkey